### PR TITLE
Add Nix support

### PR DESCRIPTION
**Pull request by layus**
/cc @sjmackenzie You may like this one ;-)

### CODE REVIEW

**Comment by sjmackenzie** [comment]
Hell yes!

**Comment by layus** [comment]
Note that it still downloads bootcompiler.jar.
Further work is needed to prefetch the scala dependencies and use sbt in offline mode. (But do we really want that ?)

**Comment by layus** [comment]
Also not that nix is, to the best of my knowledge, the only package manager that packages clang internal static libraries correctly, allowing to easily compile the generator.

**Comment by sjmackenzie** [comment]
Oh no, I highry doubt we need to bootstrap the entire process, as long as the bootstrap compiler src is there. @sjrd what's your opinion on the matter?

**Comment by sjrd** [comment]
I'm not sure what you guys are talking about right now :-s

**Pull request merged**
