### PR TITLE
[WIP] Setup travis releases

### PR DESCRIPTION
**Pull request by azarzadavila**

### CODE REVIEW

**Comment by layus** [comment]
The key was generated by travis, with azarzadavila account. I generated a new one with my own account.
Apparenlty OAuth keys are personal. There is no way to create a key for the organisation.
Let's try this, we can still fix later on.

**Comment by sjmackenzie** [comment]
Ah I see, wasn't familiar with @azarzadavila

**Comment by layus** [comment]
@sjmackenzie We just hired him to setup CI for mozart2

**Comment by sjmackenzie** [comment]
@layus ah right, okay cool understood.

**Pull request merged**
