### PR TITLE
Cache generated code & Gen source archive

### PR DESCRIPTION
**Pull request by layus**
Here is an attempt at caching the generated code to remove the dependency on LLVM/Clang at build time. The idea is to distribute full sources, which would make this project much easier to compile for packagers and users.

It works pretty well, but for some unknown reason building genboostsources still triggers the build of the generator despite the EXCLUDE_FROM_ALL tag on generator.
Strange enough, it works correctly for gensources.

Any idea on this ?

- [x] Cache gen*sources results
- [x] Fix dependency between genboostsources and generator.
- Cache library_stage_0 (not sure it is desirable)
- [x] cache version for building from a source tarball (without git info).

(Yes, cmake code could be improved by detecting cached dirs once and for all...)

### CODE REVIEW

**Comment by sjrd** [comment]
Hum ... I'm fine with the idea, but the cached files should still not be part of the git repository. We can propose downloadable tars with the generated sources, but not put them in git.

**Comment by layus** [comment]
Indeed, or we could maintain a separate git branch. This will remain blocked as long as I cannot understand why cmake is annoying me :-)

**Comment by layus** [comment]
These changes add a caching mechanism for source files generated by the generator and a 'dist' target that builds a proper source archive.
The cmake configuration has been modified to allow building within the source tarball (no access to git to get the version, use the cached files).
The caching mechanism works independently from the source tarball. It only relies on the presence of `vm/{boostenv,vm}/main/cached/*.gen`.

:warning: The build directory must reside **outside** the sourse tree lest cpack includes it in the source archive when invoking `make dist`. This is however not required for the other targets.

Anyone cares to test and review ?

**Comment by eregon** [comment]
Looks like a really good idea in general!

I don't know enough cmake to review, but I can give it a try :smiley: 

> The build directory must reside outside the sourse tree *lest* cpack includes

What is `lest`?

**Comment by eregon** [comment]
@layus How can I get the cached files so that I can try a build without setting up LLVM?

**Comment by layus** [comment]
@eregon http://dictionary.reference.com/browse/lest ;-) Not sure it is a perfect usage BTW...

**Comment by sjmackenzie** [comment]
@layus do you have nix scripts to build mozart?

**Comment by layus** [comment]
@eregon An generated archive is available here : https://transvol.sgsi.ucl.ac.be/download.php?id=a22b6172891d1bcb
It is tagged Dirty because i need some hacks to make clang work.

**Comment by layus** [comment]
@sjmackenzie not yet, but I think I may implement them on top of this source archive.

**Comment by sjmackenzie** [comment]
@layus fine idea indeed. I'll feed it into hydra.

**Comment by layus** [comment]
@sjmackenzie that being said, the current mozart package in nixpkgs [1] should work pretty well, but I have not tested it for a while.

[1] https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/mozart/binary.nix

**Comment by sjmackenzie** [comment]
yeah sure! I initially wrote that then 7c6f434c assisted me back when I was
getting started:
https://github.com/NixOS/nixpkgs/commits/master/pkgs/development/compilers/mozart

**Comment by eregon** [comment]
@layus Pretty good results!
I managed to build mozart 2 from the archive in 12 min!

Unfortunately, the auto-download of gtest seems broken so I had to get it from svn and build it, but otherwise it was pretty simple (I also needed to install the static boost libs):
```bash
$ create the directory structure
$ download and build gtest
$ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../moz2prefix \
  -DGTEST_SRC_DIR=../externals/gtest -DGTEST_BUILD_DIR=../externals/build-gtest \
  ../mozart2-2.0.0-alpha.0+build.4157.77fd9a3-dirty-Source 
$ time make -j 4  
make -j 4  2384.87s user 56.08s system 343% cpu 11:50.76 total
$ make install
```

**Comment by eregon** [comment]
The `library_stage_0` was not cached in my build. Not a big deal on this machine but on my old Macbook it would take forever since one of the files would take a lot of ram and swap.

**Comment by layus** [comment]
Yep, the archive does not contain binary files, only source files.

It is theoretically possible to cache the library_stage_0 just like the generated sources, or even the boot compiler.
The problem is that .ozf is really a binary blob.
If we cache stage_0, why not cache all the final ozf's ? 

In the end, only the Mozart VM need to be compiled on each architecture/setup.


The project requires gtest only to build tests, we could remove the vmtest from all, not building it if not required.
Updating the gtest download is also a good idea.
The last alternative is to include gtest in our sources, but this was already deemed a bad idea.

You should not need the static boost libraries if you set `-DMOZART_BOOST_USE_STATIC_LIBS=OFF`. You will however still need the headers and the dynamic libs (obviously :-) ).

Anyway, the most annoying issue for automated build systems used by distros is the boot compiler as SBT requires network access.
For now the only solution seems to provide a boot compiler.jar to the build agents.


As a side note, the policy of llvm/clang is to break internal API's all the time, so it makes sense to short circuit it in our source distribution.

**Comment by eregon** [comment]
* Yeah, I guess we might as well use the full binary distribution if we want precompiled ozf.
* gtest was very fast and easy to auto-download and compile, so fixing the auto build is more than enough for gtest. It should be fixed to a specific revision and not take the latest trunk (should be already the case). Also, it's fairly verbose in CMake options to do manually and requires a more complex dir structure.
* For a user, you most likely have to install some deps so some network activity is not a big problem (for CI neither).

**Comment by sjmackenzie** [comment]
please tag me as github doesn't inform on further pushes.

**Comment by sjmackenzie** [comment]
Touching base! How goes this PR?

**Comment by layus** [comment]
@sjmackenzie Well, it is already usable. I do not have time to clean and polish it right now, but I would love to get your feedback.
It contains fixes for dup2, and updates to new versions of clang. This should be spitted.

**Comment by sjmackenzie** [comment]
Are you referring to the merge conflicts? If so once they're cleaned up
I'll merge asap.

**Comment by layus** [comment]
I have reworked this patch set.
I however need help to test it on Windows and MasOS.
 1. Test if the source archive at https://github.com/layus/mozart2/releases/tag/v2.0.0-beta.0 contains everything for a correct build (`make && make test`)
 2. (optionnal) Test that you are able to generate the source archive, as the new system uses the packaged clangConfig.cmake. If your distribution/package manager provides llvm/clang, then this should work out of the box without building LLVM/Clang.

**Comment by layus** [comment]
@sjmackenzie There is no nix expression for mozart as we need first to understand how we can make sbt work offline. The other option is to download some binary bootcompiler, as provided on  https://github.com/layus/mozart2/releases/tag/v2.0.0-beta.0

**Comment by sjmackenzie** [comment]
I think there are use cases of `sbt` in `nixpkgs`. I'd love to see a `default.nix` in the root folder. It'll make it slightly more easy to integrate it into `nixpkgs`. Well done on this patch, if you see any more issues don't hesitate to make new pull requests, they'll be merged in asap!

**Comment by sjmackenzie** [comment]
I'm afraid I do not have a MacOS machine... actually my wife has a windows machine but it'll be a few days after unpacking as we're moving at the end of the week. So I'll give Windows a spin...

**Comment by GuillaumeDerval** [comment]
`100% tests passed, 0 tests failed out of 23` on macOS Sierra :-)

**Comment by eregon** [comment]
@sjrd 
> Hum ... I'm fine with the idea, but the cached files should still not be part of the git repository. We can propose downloadable tars with the generated sources, but not put them in git.

Just my opinion: this is pretty much like a parser generator, and almost every project out there would ship with the `parse.c/parse.java` as well as the `parse.y`, because it's just not changed often enough to justify everyone having to set it up (and compile a full LLVM/Clang!).

**Comment by sjrd** [comment]
> because it's just not changed often enough to justify everyone having to set it up

I guess that's the crucial point. And it does not apply to Mozart's case. The generated files change every time you change anything public in any `DataType` class.

**Comment by eregon** [comment]
Which is still very rare (only a handful commits changed it in the last 2 years) compared to the number of users trying to install it.
If it changed almost every commit I would agree.

**Comment by sjmackenzie** [comment]
@eregon go ahead and try it out, if you feel the experiment has failed change it back.

**Pull request merged**
